# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a28b03c8cd4706badbb7e4a0bae25b87d2d54fdd234954e027b0ce85891219cb2e1101708033f3c97a0d5272c6f6d1c017b245304dc2c4ac555eb5c2a6e44e5e

test:
  secret_key_base: db9ad5ecf58502c3677fc62bbace7838cea0ca3d267d24026063ded5594af45c7d5530d3d6ee38d67ff8b3d0affd26723b3cf0bfae225d4003d3f5056cbc5fca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
