LineLength:
  Max: 10000
MethodLength:
   Max: 30
AllCops:
  TargetRubyVersion: 2.3.3
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'bin/*'
Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

# guardClause check doesn't make sense in our context
Style/GuardClause:
  Enabled: false